theme: jekyll-theme-cayman
title: Booz Allen Open Source
description:  

.button {
  background-color: #076D75; /* Teal */
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
}
