theme: jekyll-theme-cayman
title: Booz Allen Open Source
description:  Innovate with Booz Allen using the same open source solutions we created to help our clients—federal agencies and industry leaders—develop quickly and nimbly enough to keep pace with a rapidly changing world.
<br>
Start building with a couple of our bedrock solutions or check out our public license below. For a full list of the open source technologies we’re proud to share with the larger coding community, head to our <a href="https://github.com/boozallen">GitHub organization</a>.
